"""add splitter topology

Revision ID: 44fadb83f431
Revises: 9f81d49bf54c
Create Date: 2026-03-15 02:44:07.662000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44fadb83f431'
down_revision: Union[str, Sequence[str], None] = '9f81d49bf54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splitters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('olt_id', sa.UUID(), nullable=False),
    sa.Column('pon_port', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_onu_status_id'), table_name='onu_status')
    op.drop_table('onu_status')
    op.drop_index(op.f('idx_alarms_created_at'), table_name='alarms')
    op.drop_index(op.f('idx_alarms_is_resolved'), table_name='alarms')
    op.add_column('onus', sa.Column('splitter_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'onus', ['olt_id', 'onu_index'])
    op.create_foreign_key(None, 'onus', 'splitters', ['splitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onus', type_='foreignkey')
    op.drop_constraint(None, 'onus', type_='unique')
    op.drop_column('onus', 'splitter_id')
    op.create_index(op.f('idx_alarms_is_resolved'), 'alarms', ['is_resolved'], unique=False)
    op.create_index(op.f('idx_alarms_created_at'), 'alarms', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('onu_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('frame', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('onu_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rx_power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tx_power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('onu_status_pkey'))
    )
    op.create_index(op.f('ix_onu_status_id'), 'onu_status', ['id'], unique=False)
    op.drop_table('splitters')
    # ### end Alembic commands ###
