"""add severity and escalation to alarms

Revision ID: 9f81d49bf54c
Revises: 4949f893189a
Create Date: 2026-03-03 01:33:10.203652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f81d49bf54c'
down_revision: Union[str, Sequence[str], None] = '4949f893189a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1️⃣ Tambah kolom sebagai nullable dulu
    op.add_column(
        'alarms',
        sa.Column('severity', sa.String(length=20), nullable=True)
    )
    op.add_column(
        'alarms',
        sa.Column('escalation_level', sa.Integer(), nullable=True)
    )

    # 2️⃣ Isi data lama
    op.execute("UPDATE alarms SET severity = 'medium'")
    op.execute("UPDATE alarms SET escalation_level = 0")

    # 3️⃣ Ubah jadi NOT NULL
    op.alter_column('alarms', 'severity', nullable=False)
    op.alter_column('alarms', 'escalation_level', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarms', 'escalation_level')
    op.drop_column('alarms', 'severity')
    # ### end Alembic commands ###
